### ISSUE TITLE
!! Alle code verdwijnt als je twee keer op "code bewerken" klikt.

### ISSUE THREAD

**Issue by MightyJort** [leaphy-robotics/leaphy-client#148]
Er gebeurd precies wat er in de titel staat. De versie easybloqs is: 
"Versie 1.0.6-pre.10 (1.0.6-pre.10)" 
Op MacOs Big Sur 11.5.2 
In de bijlage zit een schermopname waarin het gebeurd. Belangrijk dat dit opgelost wordt, ik ben een halfuur werk kwijtgeraakt.

https://user-images.githubusercontent.com/47349377/134159918-c32a4c9c-7577-4ec5-af51-ae07dbfc913a.mov

Dit is de log die erbij hoort:
Error during Upload: uploading error: uploading error: exit status 1

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
[2021-09-21 12:43:27.087] [info]  
 0 / 410803    0.00%
Updating index: package_index.json downloaded

 0 / 543    0.00%
Updating index: package_index.json.sig downloaded

[2021-09-21 12:51:31.984] [error] stderr: avrdude: stk500_loadaddr(): (a) protocol error, expect=0x14, resp=0x10

[2021-09-21 12:52:42.575] [error] stderr: avrdude: stk500_loadaddr(): (a) protocol error, expect=0x14, resp=0x10

https://user-images.githubusercontent.com/47349377/134159820-7a6682e4-7de7-429f-bea3-d1e85b9e4a13.mov

**Comment by paulsiersma** [comment]
Hoi @MightyJort  oh dat is een vervelende bug inderdaad. Ik ga er zsm mee aan de slag!
