### ISSUE TITLE
Compilation error - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by paulsiersma** [leaphy-robotics/leaphy-client#99]
[2021-04-09 15:17:47.372] [error] Compilation failed! Error: Command failed: C:\Users\djgab\AppData\Local\Temp\3266653f-189c-4af5-9691-d195501d3ee0.tmp.exe compile --fqbn arduino:avr:uno C:\Users\djgab\AppData\Roaming\easybloqs\sketch\sketch.ino --build-path C:\Users\djgab\AppData\Roaming\easybloqs\sketch

panic: runtime error: invalid memory address or nil pointer dereference

[signal 0xc0000005 code=0x0 addr=0x0 pc=0xd9d905]

goroutine 1 [running]:

github.com/arduino/go-properties-orderedmap.(*Map).Get(...)

/github/home/go/pkg/mod/github.com/arduino/go-properties-orderedmap@v1.3.0/properties.go:223

github.com/arduino/arduino-cli/legacy/builder.(*WipeoutBuildPathIfBuildOptionsChanged).Run(0x19e8750, 0xc0003f6000, 0x19e8750, 0x0)

/__w/arduino-cli/arduino-cli/legacy/builder/wipeout_build_path_if_build_options_changed.go:48 +0x1d5

github.com/arduino/arduino-cli/legacy/builder.(*ContainerBuildOptions).Run(0x19e8750, 0xc0003f6000, 0x19e8750, 0x0)

/__w/arduino-cli/arduino-cli/legacy/builder/container_build_options.go:35 +0x128

github.com/arduino/arduino-cli/legacy/builder.runCommands(0xc0003f6000, 0xc000529248, 0x20, 0x20, 0x0, 0x0)

/__w/arduino-cli/arduino-cli/legacy/builder/builder.go:187 +0x1a6

github.com/arduino/arduino-cli/legacy/builder.(*Builder).Run(0xc0005294c0, 0xc0003f6000, 0x1255100, 0xc000653a70)

/__w/arduino-cli/arduino-cli/legacy/builder/builder.go:97 +0xb89

github.com/arduino/arduino-cli/legacy/builder.RunBuilder(...)

/__w/arduino-cli/arduino-cli/legacy/builder/builder.go:205

github.com/arduino/arduino-cli/commands/compile.Compile(0x124c100, 0xc000034138, 0xc000529c70, 0x12320e0, 0xc000006018, 0x12320e0, 0xc000006020, 0x0, 0x0, 0x0, ...)

/__w/arduino-cli/arduino-cli/commands/compile/compile.go:215 +0x17ac

github.com/arduino/arduino-cli/cli/compile.run(0xc00031eb00, 0xc0001af450, 0x1, 0x5)

/__w/arduino-cli/arduino-cli/cli/compile/compile.go:155 +0x412

github.com/spf13/cobra.(*Command).execute(0xc00031eb00, 0xc0001af400, 0x5, 0x5, 0xc00031eb00, 0xc0001af400)

/github/home/go/pkg/mod/github.com/spf13/cobra@v1.0.1-0.20200710201246-675ae5f5a98c/command.go:846 +0x2b1

github.com/spf13/cobra.(*Command).ExecuteC(0xc0001db340, 0x0, 0xc0002bad80, 0x0)

/github/home/go/pkg/mod/github.com/spf13/cobra@v1.0.1-0.20200710201246-675ae5f5a98c/command.go:950 +0x350

github.com/spf13/cobra.(*Command).Execute(...)

/github/home/go/pkg/mod/github.com/spf13/cobra@v1.0.1-0.20200710201246-675ae5f5a98c/command.go:887

main.main()

/__w/arduino-cli/arduino-cli/main.go:31 +0x8c

**Comment by paulsiersma** [comment]
This PR in arduino-cli project is related it seems: https://github.com/arduino/arduino-cli/pull/1118

**Comment by paulsiersma** [comment]
Can reproduce by corrupting C:\Users\<user>\AppData\Roaming\easybloqs\sketch\build.options.json

**Comment by paulsiersma** [comment]
@Roelandsmith I think this can be considered closed. Feel free to reopen if there is still work to be done on this.
